# Generated by Django 5.1.4 on 2024-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='homeslider/%Y/%m/%d/', verbose_name='Фото')),
                ('title', models.CharField(help_text='Внимательнее', max_length=100, verbose_name='Заголовок слайда')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': ('Слайд',),
                'verbose_name_plural': ('Слайды',),
            },
        ),
    ]
