# Generated by Django 5.1.4 on 2024-12-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_homeslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
