# Generated by Django 5.1.4 on 2024-12-11 12:44

import blog_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_homeslider_options_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog_app.models.post_gallery_image_path, verbose_name='Фото')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.todo', verbose_name='Пост')),
            ],
        ),
    ]
