# Generated by Django 5.1.4 on 2024-12-11 13:10

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_todogallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todogallery',
            name='image',
            field=models.ImageField(upload_to=blog_app.models.post_gallery_image_path),
        ),
    ]
